export const SUB_HUNDRED_ES: any = {
  0   : 'cero',
  1   : 'uno',
  2   : 'dos',
  3   : 'tres',
  4   : 'cuatro',
  5   : 'cinco',
  6   : 'seis',
  7   : 'siete',
  8   : 'ocho',
  9   : 'nueve',
  10  : 'diez',
  11  : 'once',
  12  : 'doce',
  13  : 'trece',
  14  : 'catorce',
  15  : 'quince',
  16  : 'dieciséis',
  17  : 'diecisiete',
  18  : 'dieciocho',
  19  : 'diecinueve',
  20  : 'veinte',
  21  : 'veintiuno',
  22  : 'veintidós',
  23  : 'veintitrés',
  24  : 'veinticuatro',
  25  : 'veinticinco',
  26  : 'veintiséis',
  27  : 'veintisiete',
  28  : 'veintiocho',
  29  : 'veintinueve',
  30  : 'treinta',
  40  : 'cuarenta',
  50  : 'cincuenta',
  60  : 'sesenta',
  70  : 'setenta',
  80  : 'ochenta',
  90  : 'noventa',
  100 : 'cien',
};

export const TENTH_MAPPING_ES: any = {
  30  : 'treinta y',
  40  : 'cuarenta y',
  50  : 'cincuenta y',
  60  : 'sesenta y',
  70  : 'setenta y',
  80  : 'ochenta y',
  90  : 'noventa y',
  100 : 'ciento',
  200 : 'doscientos',
  300 : 'trescientos',
  400 : 'cuatrocientos',
  500 : 'quinientos',
  600 : 'seiscientos',
  700 : 'setecientos',
  800 : 'ochocientos',
  900 : 'novecientos',
};

export const SUFFIX_MAPPING_ES: any = {
  30: 'y',
  40: 'y',
  50: 'y',
  60: 'y',
  70: 'y',
  80: 'y',
  90: 'y',
  100: 'ciento',
};

export enum OtherWordsEs {
  minus = 'menos',
  point = 'punto'
}
